### ISSUE TITLE
Обсуждение правок мобильной версии!

### ISSUE THREAD

**Issue by paramaxstudio** [warks89/brigadi#109]
1. Функция-кнопка "Предложить работу" на мобильной версии не должна работать ( панелька дополнительная НЕ появляется), предлагаю саму кнопку "предложить работу" оставить возле каждого исполнителя, но на мобильное версии все эти кнопки ведут на форму добавления заказа.

2. Форма добавления заказа на мобильной версии - сделать четкой шапку с заголовком "Мастера поборются за ваш заказ"
![image](https://cloud.githubusercontent.com/assets/10115629/9575801/1f1a62a2-4fdb-11e5-9cbc-bed3ca90bdc7.png)

3. Внизу как вариант сделать длинную кнопку перейти на следующую страницу.
![image](https://cloud.githubusercontent.com/assets/10115629/9575783/0abb0668-4fdb-11e5-81e5-e03b6b664241.png)
 
4. Весртка прайса и рекламного текста строителей на мобильной версии - поработаь
Текст как вариант растянуть на ширину, прайс - тестить вариант, при котором все переносится и экономится место.
![image](https://cloud.githubusercontent.com/assets/10115629/9575898/d3edbf26-4fdb-11e5-9b9c-1f573443a4a8.png)

5. Фото работ раздел - доверстать под мобильные устройства

**Comment by Dekap** [comment]
Важные, Нужно исправить:
1 По первому пункту - Возможно как временное решение. Лучше сразу продумать верстку, что бы панелька не занимала более одной трети рабочего экрана.
2 а) Слетает текст на телефоне в строчках прайса при вертикальном отображении. 
![screenshot_2015-08-31-08-20-44]
(https://cloud.githubusercontent.com/assets/10116028/9575405/1cb53a3a-4fd8-11e5-876e-01b62eadb102.png)
б) Здесь же, рекламный текст "устройство промышленных полов " разумно растянуть на всю ширину экрана, не ограничевая его до иконки.

Косяки, которые нужно исправить, но сайт может функционировать и с ними:
1) http://brigadi.by/portfolio/
эта страница не сверстана для мобильной версии, сильно уменьшаются кнопки меню или не влазят фото 
![screenshot_2015-08-31-08-28-00](https://cloud.githubusercontent.com/assets/10116028/9575486/ea3df3e8-4fd8-11e5-8093-2c27184664d0.png)
Растянуть меню навигации также как и на других разделах.

2) Страничная навигация : 
![screenshot_2015-08-31-08-25-09](https://cloud.githubusercontent.com/assets/10116028/9575516/1b036922-4fd9-11e5-8081-b71f261316c1.png)
Долго соображал почему не действует переход при нажатии на "...", и для того что бы перейти на след страницу нужно нажать "кавычки" справа + очень мелкие кнопки.
Пример лечения - большая кнопка показать еще как на ремонтнике
![screenshot_2015-08-31-12-12-59](https://cloud.githubusercontent.com/assets/10116028/9575643/dff93bb2-4fd9-11e5-8a27-e276e0199e89.png)
По нажатию контент удобно подгружается и готов к просмотру.
Очень удобно не только для мобильной версии. Функционал перейти на страницу - на мой взгляд просто не нужен, а с этой кнопкой тем более.
