### ISSUE TITLE
Добавить для не очень умных юзеров (текст внутри)

### ISSUE THREAD

**Issue by toppoc** [warks89/brigadi#116]
Модератор отклонит фотографию если:
 1.  На ней изображена чужая работа, а так же фотографии созданные в графическом редакторе.    
 2. Фотография не относится к теме портфолио
 3. В подписи к фотографии и на самой фотографии содаржатся адреса и логотипы других сайтов, e-mail, номера телефонов или ICQ.
 4. Фотография в очень плохом качестве и/или очень мала

 По любым вопросам звоните по телефонам 8-029-325-70-70, 8-033-325-70-70
 BRIGADY.BY

![12](https://cloud.githubusercontent.com/assets/13044859/9606351/9f120d52-50cb-11e5-9a29-17723bdf548d.png)

**Comment by warks89** [comment]
Сделаем в виде tooltip для каждого поля
