### ISSUE TITLE
доработка верстки

### ISSUE THREAD

**Issue by paramaxstudio** [warks89/brigadi#135]
![image](https://cloud.githubusercontent.com/assets/10115629/9683053/093ab2e2-5315-11e5-8d20-40bafe2323b5.png)

**Comment by warks89** [comment]
на какой это странице?

**Comment by paramaxstudio** [comment]
мастера

**Comment by paramaxstudio** [comment]
надо посмотреть футер и не других страницах, убрать лишнее

**Comment by warks89** [comment]
Там стоит проверка на наличие символов. В данном случае там введен 1 enter и 1 пробел.
