### ISSUE TITLE
Важно: доходят не все смс

### ISSUE THREAD

**Issue by Dekap** [warks89/brigadi#154]
http://brigadi.by/admin/index.php?s=users&ev=user_edit&members=1&tuid=2c883836ae5ebb960adf89433098708c&rec=32%22;%22http://brigadi.by/admin/index.php?s=users&ev=user_edit&members=1&tuid=2c883836ae5ebb960adf89433098708c&rec=32%22

Говорит что не доходят смс о новых заказах. Он подписан на "Комплексные услуги / Ремонт квартир и домов" и все птички проставлены. За вчера были 2 новых заказов
http://brigadi.by/?orders=remont-kvartir-i-domov&page=1
Но смс нет как в админке бригад, так и в админке вебсмс

**Comment by warks89** [comment]
По статистике во норм стало отправляться, с 25 числа ушло 4 смски
