### ISSUE TITLE
На сайте при вводе адресов иногда выдает другие города

### ISSUE THREAD

**Issue by toppoc** [warks89/brigadi#161]
Например карла маркса 42, есенина 23

Ввожу адрес, жму найти
![144444](https://cloud.githubusercontent.com/assets/13044859/9991269/56d5903a-6071-11e5-932e-eccd8a8f9a2c.png)

И вот такое вот выдает
![4444444](https://cloud.githubusercontent.com/assets/13044859/9991270/56dad0e0-6071-11e5-8c26-bc84a853343a.png)

**Comment by warks89** [comment]
По другому никак, для указания правильного адреса надо дописывать минск. Если разбираться в приоритетах и прочем  займет около 1-2 дней с тестированием. Пока считаю не актуальным и закрываю.
