### ISSUE TITLE
Требуется прикрутить расшатавшийся унитаз

### ISSUE THREAD

**Issue by warks89** [warks89/brigadi#199]
Исполнитель на сайте есть, но  в админке нету исполнителя и отзывов у него

**Comment by warks89** [comment]
http://brigadi.by/orders/652-perenos-dvernogo-projema.html еще один пример

**Comment by toppoc** [comment]
http://goo.gl/aEunjP вот у этого юзера вот такая фигня
![123](https://cloud.githubusercontent.com/assets/13044859/10609269/9189829a-774b-11e5-9860-9e5bacb17012.png)
![321](https://cloud.githubusercontent.com/assets/13044859/10609270/919fb844-774b-11e5-91ea-2d91edab648b.png)
