### ISSUE TITLE
При переходе по ссылке "Изменить прайс" в настройках личного кабинета

### ISSUE THREAD

**Issue by warks89** [warks89/brigadi#200]
Перекидывает на общую страницу. Избавиться от одного лишнего клика

**Comment by toppoc** [comment]
кнопка ( 1 на картинке ) ведет на общую ( 2 на картинке ) а надо в настройки цен ( 3 на картинке )

![1](https://cloud.githubusercontent.com/assets/13044859/10756976/a99eb9a0-7cb8-11e5-9496-fd789b4b49db.png)
