### ISSUE TITLE
Тз на аккаунты для мастеров

### ISSUE THREAD

**Issue by paramaxstudio** [warks89/brigadi#208]
1.	Бесплатный аккаунт

Нет доступа к заказам. (Нет возможности отвечать на заказы – выводится сообщение: Для ответа на заказы необходима платная подписка. Обратитесь к менеджеру по телефону: +375 ….

Предполагает простое размещение в каталоге внизу списка ( после спецаккаунтов и про аккаунтов). В карточке можно запросить контакты мастера ( как это работает сейчас)

2.	Стандарт+
           Доступы ко всем заказам, кроме комплексных работ ( это будет около 
3-5 избранных специализаций – типа «Ремонт квартир и домов» и еще    парочку ) – тут вопрос можно ли будет потом что-то добавить в комплексные…

3.	Премиум
Доступы ко всем заказам с комплексными 

+ для каждого аккаунт будут добавляться свои сроки период оплаты 
С …ДО

Рассмотреть возможно сделать это на основе функционала текущего pro аккаунты

**Comment by Dekap** [comment]
задача реализована, можно закрывать
