### ISSUE TITLE
Список важных правок

### ISSUE THREAD

**Issue by paramaxstudio** [warks89/brigadi#22]
3. Обсудить вывод прайса для корневой специализации для конкретного юзера(сейчас походу берется первые 3) для всех юзеров - получается заходишь в плиточные работы, а там у всех прайс: укладка мозаики, укладка мозаики, укладка мозаики.... может сделать "птичку" - юзер сможет указать 3 строчки прайса, которые выводить конкретно для него в разделе, например, Плиточные работы

Подключить по API WebSMS.by Текст уведомлений настраивается в рубрике шаблоны рассылок
( Вова уже ставил эту рассылку на Флэтбук)
Рассылка СМС:
-------------Заказы: Новый заказ (мгновенная отправка)
Шаблон письма, отправляемого исполнителю при создании нового заказа в одну из его специализаций.
 Все строители которые находятся в данной рубрике - получают смс: типа "По вашей специализации добавлен новый заказ "Монтаж потолков"
СМС высылается только после того как модератор проверил заказ и если нужно (если пользователь не выбрал или выбрал неправильно) изменил специализацию / добавил.
-------------Сообщения: Новое сообщение
Шаблон письма, отправляемого пользователю при получении нового сообщения
- Вас выбрали исполнителем. только уведомлять об этом статусе
Вообще остальные статусы лучше из параметров рассылки вообще убрать
- Вы получили отказ. - Вас выбрали кандидатом.
Зачем расстраивать людей.

**Comment by Dekap** [comment]
В компаниях по дибильному обрезается логотип
Обсуждается, пока не делать

**Comment by Dekap** [comment]
Полетела привязка динамических разделов к прайсу. раздел "натяжные потолки" заменился на "двери...", обратно не пересохраняется
http://gyazo.com/08c992198e223276505732615f5aafa2

Исправить, разобраться почему слетела привязка - что бы не делать эту работу еще раз заново (Должна быть возможность добавлять - удалять - реактировать разделы в динамике без таких косяков)

**Comment by Dekap** [comment]
из-за того что пользователь, указав цену услуги в нужном разделе динамики, не будет выводится там же пока не укажет (продублирует) птичкой эту же категорию. Возникла сложность. Мы просто не знаем сколько человек (из тех что заполнили прайс) тыкнули на эти птички. Те нужно уйти от дублирования к схеме - указал цену - вывелся (а связь услуги задается в админке для всех сразу)
