### ISSUE TITLE
Важно. Вывести рекламный блок на стр. заказа

### ISSUE THREAD

**Issue by Dekap** [warks89/brigadi#227]
В поиске начали вылазить страницы с заказами:
https://yandex.by/search/?rdrnd=83298&text=%D0%BC%D0%B5%D0%BB%D0%BA%D0%B8%D0%B9%20%D0%B1%D1%8B%D1%82%D0%BE%D0%B2%D0%BE%D0%B9%20%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D1%82&lr=157&redircnt=1447312184.1
https://yandex.by/search/?rdrnd=650244&text=%D0%BA%D1%83%D0%BF%D0%B8%D1%82%D1%8C%20%D0%B7%D0%B0%D0%B4%D0%BD%D1%8F%D1%8F%20%D1%81%D1%82%D0%B5%D0%BD%D0%BA%D0%B0%20%D0%B2%20%D1%82%D1%83%D0%B0%D0%BB%D0%B5%D1%82%D0%B5%20%D1%84%D0%BE%D1%82%D0%BE%20%D0%BF%D0%BB%D0%B8%D1%82%D0%BA%D0%B0&lr=157&redircnt=1447312073.1

и др.

Поэтому нужно мотивировать случайных посетителей оставить заказ и на этих страницах.
Взять решение ремонтника:
https://www.remontnik.ru/boards/kanalizatsiia-v-zagorodnom-dome-379172
https://www.remontnik.ru/boards/maliarnye-raboty-oboi-379113
и перенести к нам 1 к одному с поправками на дизайн.
https://gyazo.com/e85498c4e4fcecae145635a6bda89042

Кроме этого желательно вывести статус заказа (исполнитель, отзывы) как в левом блоке на странице добавления заказа
https://gyazo.com/9f87594edbcf0ccd48ae4db8368c2953

**Comment by toppoc** [comment]
http://SSMaker.ru/ca899873/ работает, только выглядит криво
