### ISSUE TITLE
Обсудит ьколичество изображений при добавлении заказа

### ISSUE THREAD

**Issue by warks89** [warks89/brigadi#230]
возможно сделать как на ремонтнике https://www.remontnik.ru/boards/kapitalnyi-remont-kvartiry-58m2-po-dizainu-379277

**Comment by Dekap** [comment]
Увеличить лимит прикрепляемых фото в заказе с 1 до 10.

**Comment by toppoc** [comment]
http://SSMaker.ru/e33bc6dd/

+ фотки не удаляются из отзыва

Лимит фото стоит 8
