### ISSUE TITLE
Сео, работа с урлами

### ISSUE THREAD

**Issue by Dekap** [warks89/brigadi#241]
В теге canonical указаны урлы без верхней категории, но в главном меню, а также на других страницах, например в профайле юзера ссылка идет с верхней категорией. Получается ситуация, когда пользователь переходит по ссылкам, которые по умолчанию не попадут в индекс. Те мы возможно теряем дополнительный фактор ранжирования целевых страниц. Если коротко - зачем высоко поднимать в поиске страницы сайта, если на самом сайте их никто не просматривает.
https://gyazo.com/3b8800a19bbe94ebd720736d4d96580f
https://gyazo.com/a1b55b3f1c62b7057131cb2a13e65636

Просмотри, сможешь сделать так, что бы ссылка в любом месте (меню, профайл и тд) не вкл верхний уровень вложенности.
Или задача от обратного - добавить в тег каноникл верхний уровень вложенности. Это возможно намного проще.
------------------------------

Пока просто изучи, любые правки по урлам могут приведут к временному падению трафика. Интересно услышать их мнение поддержки таморанги

**Comment by warks89** [comment]
сделал короткие урл на общей странице мастеров и на странице профиля. Если еще будут страницы, то скидывай в коммент и переоткрывай таск

**Comment by Dekap** [comment]
http://brigadi.by/sitemap/
