### ISSUE TITLE
Меню навигации

### ISSUE THREAD

**Issue by Dekap** [warks89/brigadi#244]
Сложно вернуться на станицу раздела каталога, после массового просмотра портфолио
http://webvisor.com/inpage/visor-player?id=31468318&date=2015-11-19&visit_id=5930684737335521403&watch_id=&user_id_hash=3014286596&dn=&tld=ru

Пользователь использовал кнопку в браузере для возврата к списку мастеров в разделе. Когда он начал просматривать партфолио, возникла необходимость возврата по прямой ссылке. Его действия - просмотрел меню, меню навигации, и только после этого начал искать в списке "специализаций".
Вывод - должна быть прямая ссылка для возврата на нужную категорию, с которой был совершен переход в профайл и далее.

П.с.
Ремонтник частично решил этот вопрос тем, что у него все партфолио открываются в отдельных окнах, не влияющих на кнопку назад. Т.е кол-во кликов "назад" у него ограничено вкладками.

**Comment by Dekap** [comment]
На фб - этот вопрос попробовали решить через "Вернуться к результатам поиска" (похоже запоминает данные первого введенного фильтра)

**Comment by coolkabro** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/10129275/11333041/d390d472-91db-11e5-9da7-2a59a6bc5202.png)
