### ISSUE TITLE
Вернуть полные хлебные крошки + мастера

### ISSUE THREAD

**Issue by warks89** [warks89/brigadi#245]
в хлебных крошках мастера писать категорию из которой перешли на эту страницу со страницы каталога

например : Бригады/ мастера/ фасадные работы / Игорь

**Comment by Dekap** [comment]
например : Бригады/ мастера/ фасадные работы / Игорь
лучше так : Бригады/ мастера/ фасадные работы
игрорь в данном случае будет сразу под хлебными крошками (ФИО)

а вот на на странице каталога текущий раздел в хлебных крошках нужно добавить, но например сделать его не активным как здесь http://kaska.pro/stroiteli-i-brigadi/elektriki.html
