### ISSUE TITLE
Для Андрея, верстка

### ISSUE THREAD

**Issue by toppoc** [warks89/brigadi#276]
1. Фотографии к заказу - барабан показывает только 5. Пока попросил вову поставить лимит в 5 штук.

2. Фотографии к отзыву - расположены вертикально, смотрится не очень.

3. Кнопка только на половину кликабельна.
![1](https://cloud.githubusercontent.com/assets/13044859/12546119/a124475e-c358-11e5-8988-e4c327c6db82.png)

**Comment by toppoc** [comment]
Без комментариев
![12](https://cloud.githubusercontent.com/assets/13044859/12808153/dc936796-cb25-11e5-9cfb-ff7dd40f461f.png)

**Comment by warks89** [comment]
Вертикальные фотки надо либо перерезать, либо  лучше вписать их в дизайн. Они все нарезаны 200х200. Остальное поправил
