### ISSUE TITLE
Невозможно перейти к общему списку после выбора специализации. (внутри)

### ISSUE THREAD

**Issue by coolkabro** [warks89/brigadi#28]
Если авторизоваться за исполнителя, зайти в заказы и выбрать какую-нибудь категорию
http://SSMaker.ru/87079f73/
вернуться назад к полному списку нельзя.
Так же и со стороны заказчика при добавлении заказа, выбрав любую специализацию к начальному виду (http://SSMaker.ru/a8507afa/) вернуться уже нельзя.

**Comment by Dekap** [comment]
первый пунк вова сделал (Проверь)
актуален ли второй?

**Comment by coolkabro** [comment]
1 работает
2 не актуален, специализация присваевается модератором
