### ISSUE TITLE
Не отображать пользователей без ценников. В админке по умолчанию присваивать динамические свойства.

### ISSUE THREAD

**Issue by toppoc** [warks89/brigadi#35]
![1](https://cloud.githubusercontent.com/assets/13044859/8825489/29c1df7c-3088-11e5-8ba3-701563c304c7.png)
![2](https://cloud.githubusercontent.com/assets/13044859/8825513/6e95b0ba-3088-11e5-9310-bb2cf2bf62b1.png)

**Comment by Dekap** [comment]
Работа с прайсом. Это более глубокая задача. Займемся ей целиком, но позже
