### ISSUE TITLE
Рассмотреть. Может убрать возможность редактирования поля с унп?

### ISSUE THREAD

**Issue by coolkabro** [warks89/brigadi#43]
http://SSMaker.ru/60147410/

**Comment by Dekap** [comment]
если юзер сам отредактировал это поле, это правка уходит на Модерацию?

**Comment by warks89** [comment]
можно убрать редактирование. На модерацию эта правка не уходит

**Comment by warks89** [comment]
убрал возможность редактирования с поля "УНП"
