### ISSUE TITLE
не вписывается последняя цифры если вначале +

### ISSUE THREAD

**Issue by paramaxstudio** [warks89/brigadi#67]
![image](https://cloud.githubusercontent.com/assets/10115629/9036908/bf34bbc8-39ee-11e5-89f0-ba135437852c.png

**Comment by Dekap** [comment]
Поясню:
сейчас стоит лимит на кол-во символов и ввести номер с пробелами (например +375 29 000 00 00) Не получится. Не хватит последней цифры. Кроме этого система отправляет только первые 13 цифр, остальные обрезает, при этом учитывают пробелы и номер иногда может придти в обрезанном виде.
Предлагаю сделать стандартный шаблон. 
+375 XX XXX XX XX

**Comment by Dekap** [comment]
пример реализации:
http://myfin.by/bank/ideabank/kredity

Продублировать во всех формах:
http://brigadi.by/user/register
http://brigadi.by/orders/add
