### ISSUE TITLE
Сделать ввод цены обязательным при поставлении галочки в прайсе!!!

### ISSUE THREAD

**Issue by coolkabro** [warks89/brigadi#76]
http://SSMaker.ru/7a20360a/ админка
http://SSMaker.ru/d1830084/ профиль исполнителя

**Comment by Dekap** [comment]
Доберешься до этой задачи - отпиши. 
Кроме обязательного заполнения 3-х цен с категории, парни просили еще дать возможность "добавлять свою услугу"
